version: '3.4'

services:
  banco_postgres: 
    image: postgres:latest
    hostname: bd_financeiro_pessoal
    restart: always
    ports:
        - 5432:5432
    environment:
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "&Fin@nceiroPesso@l2023"
        POSTGRES_DB: "financeiro_pessoal" 
    volumes:
        - D:\DOCKER-VOLUMES\financeiro-pessoal\dados:/var/lib/postgresql/data
      
  financeiropessoal.api:
    image: ${DOCKER_REGISTRY-}financeiropessoalapi
    build:
      context: .
      dockerfile: FinanceiroPessoal.API/Dockerfile 
    ports:
       - 8002:80
       - 8003:443  
    restart: always
    environment:
       connection_string: "User ID=postgres;Password=&Fin@nceiroPesso@l2023;Host=bd_financeiro_pessoal;Port=5432;Database=financeiro_pessoal;Pooling=true;"
       DROP_DATA_BASE: 1
       POPULAR_DATA_BASE: 1

  sgdb: 
    image: dpage/pgadmin4
    hostname: sgdb_pgadmin4
    environment:
        PGADMIN_DEFAULT_EMAIL: "admin@teste.com.br"
        PGADMIN_DEFAULT_PASSWORD: "&Fin@nceiroPesso@l2023"
    ports:
        - 8085:80 
    volumes:
        - D:\DOCKER-VOLUMES\financeiro-pessoal\pgadmin:/var/lib/pgadmin
