version: '3.4'

services:
  banco_postgres: 
    image: postgres:14.7
    hostname: bd_financeiro_pessoal
    restart: always
    ports:
        - 5432:5432
    environment:
        POSTGRES_PASSWORD: "&Fin@nceiroPesso@l2023"
      
  financeiropessoal.api:
    image: ${DOCKER_REGISTRY-}financeiropessoalapi
    build:
      context: .
      dockerfile: FinanceiroPessoal.API/Dockerfile
    environment:
       connection_string: "User ID=postgres;Password=&Fin@nceiroPesso@l2023;Host=bd_financeiro_pessoal;Port=5432;Database=financeiro_pessoal;Pooling=true;"
